CREATE TABLE IF NOT EXISTS students (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) DEFAULT NULL,
    age INT DEFAULT NULL,
    name_kana VARCHAR(50) DEFAULT NULL,
    nickname VARCHAR(50) DEFAULT NULL,
    mailaddress VARCHAR(50) DEFAULT NULL,
    live VARCHAR(50) DEFAULT NULL,
    sex VARCHAR(50) DEFAULT NULL,
    remark VARCHAR(20) DEFAULT NULL,
    is_deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID)
    );

CREATE TABLE IF NOT EXISTS students_courses (
    id_bigint BIGINT NOT NULL AUTO_INCREMENT,
    students_ID BIGINT NOT NULL,
    course_name VARCHAR(50) NOT NULL,
    start DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    endplan DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id_bigint)
    );
