name: Java CD

on:
  pull_request:
    branches:
      - main

env:
  SRC_PATH: 'build/libs/*.jar'
  DEST_PATH: '/home/ec2-user/StudentManagement.jar'

jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run tests
        run: ./gradlew test --stacktrace

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: build/reports/tests/test

      - name: Build with Gradle Wrapper
        run: ./gradlew bootJar

      - name: SCP Copy Application to EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > private_key
          chmod 600 private_key

          scp -o StrictHostKeyChecking=no -i private_key \
            $SRC_PATH \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:$DEST_PATH

          rm -f private_key

      - name: SSH Application Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          envs: DEST_PATH
          script: |
            if [ -f /etc/systemd/system/StudentManagement.service ]; then
              echo "already exists Service File"
            else
              sudo tee /etc/systemd/system/StudentManagement.service > /dev/null <<EOF
              [Unit]
              Description=StudentManagement App

              [Service]
              ExecStart=java -jar ${DEST_PATH}
              Restart=no
              Type=simple
              User=ec2-user
              Group=ec2-user
              SuccessExitStatus=143

              [Install]
              WantedBy=multi-user.target
              EOF
            fi

            sudo systemctl daemon-reload

            if systemctl is-active --quiet StudentManagement; then
              sudo systemctl restart StudentManagement
            else
              sudo systemctl start StudentManagement
            fi
